ash_list = list(name = "ash", alias = "incisive instigator", 
                season = 11, type = "offensive",
                passive = "marked for death", 
                tactical = "arc snare", 
                ultimate = "phase breach",
                passive_desc = "Ash's map shows the location of recent deathboxes. Press on a deathbox to mark surviving attackers (once per box).",
                tactical_desc = "Throw a spinning snare that damages and tethers the first enemy that gets too close.",
                ultimate_desc = "Tear open a one-way portal to a targeted location.",
                cooldown = 25,
                charge = 2)

bangalore_list = list(name = "bangalore", alias = "professional soldier", 
                                 season = 0, type = "offensive",
                                 passive = "double time", 
                                 tactical = "smoke launcher", 
                                 ultimate = "rolling thunder",
                      passive_desc = "Fire a high-velocity smoke canister that explodes into a smoke wall on impact.",
                      tactical_desc = "Taking fire while sprinting makes you move faster for a brief time.",
                      ultimate_desc = "Call in an artillery strike that slowly creeps across the landscape.",
                      cooldown = 33,
                      charge = 3)

bloodhound_list = list(name = "bloodhound", alias = "technological tracker", 
                season = 0, type = "recon",
                passive = "tracker", 
                tactical = "eye of the allfather", 
                ultimate = "beast of the hunt",
                passive_desc = "Foes leave behind clues for you to find.",
                tactical_desc = "Briefly reveal enemies, traps, and clues through all structures in front of you.",
                ultimate_desc = "Transform into the ultimate hunter. Enhances your senses, allowing you to see cold tracks and move faster. downing opponents extend duration.",
                cooldown = 25,
                charge = 3)

caustic_list = list(name = "caustic", alias = "toxic trapper", 
                       season = 0, type = "defensive",
                       passive = "nox vision", 
                       tactical = "nox gas trap", 
                       ultimate = "nox gas grenade",
                    passive_desc = "You gain threat vision on enemies moving though your gas.",
                    tactical_desc = "Place up to 6 canisters that release deadly Nox gas when shot or triggered by enemies.",
                    ultimate_desc = "Blankets a large area in Nox gas.",
                    cooldown = 20,
                    charge = 3)

crypto_list = list(name = "crypto", alias = "surveillance expert", 
                season = 3, type = "recon",
                passive = "neurolink", 
                tactical = "surveillance drone", 
                ultimate = "drone emp",
                passive_desc = "Crypto and his teammates see what the Surveillance Drone detects up to a 30-meter radius.",
                tactical_desc = "Deploys an aerial drone. 40-second cooldown if destroyed.",
                ultimate_desc = "Charge up an EMP blast from your drone. Deals 50 shield damage, slows players, and disables traps.",
                cooldown = 40,
                charge = 3)

fuse_list = list(name = "fuse", alias = "explosives enthusiast", 
                 season = 8, type = "offensive",
                 passive = "grenadier", 
                 tactical = "knuckle cluster", 
                 ultimate = "the motherlode",
                 passive_desc = "Stack an extra grenade per inventory slot. Fire grenades farther, faster, and more accurately.",
                 tactical_desc = "Launch a cluster bomb that continuously expels airburst explosives on impact.",
                 ultimate_desc = "Launch a bombardment that encircles a target in a wall of flame.",
                 cooldown = 20,
                 charge = 2)

gibraltar_list = list(name = "gibraltar", alias = "shielded fortress", 
                   season = 0, type = "defensive",
                   passive = "gun shield", 
                   tactical = "dome of protection", 
                   ultimate = "defensive bombardment",
                   passive_desc = "Aiming down sights deploys a gun shield that blocks incoming fire.",
                   tactical_desc = "Blocks incoming and outgoing attacks.",
                   ultimate_desc = "	Call in a concentrated mortar strike on a marked position.",
                   cooldown = 30,
                   charge = 4.5)

horizon_list = list(name = "horizon", alias = "gravitational manipulator", 
                   season = 7, type = "offensive",
                   passive = "spacewalk", 
                   tactical = "gravity lift", 
                   ultimate = "black hole",
                   passive_desc = "Increase air control and reduce fall impacts with Horizon’s custom spacesuit.",
                   tactical_desc = "Reverses the flow of gravity, lifting players upward and boosting them outward when they exit.",
                   ultimate_desc = "Deploy N.E.W.T. to create a micro black hole that pulls players in towards it.",
                   cooldown = 20,
                   charge = 3)

lifeline_list = list(name = "lifeline", alias = "combat medic", 
                     season = 0, type = "support",
                     passive = "combat revive", 
                     tactical = "d.o.c. heal drone", 
                     ultimate = "care package",
                     passive_desc = "Deploy D.O.C to revive teammates, leaving Lifeline free to defend.",
                     tactical_desc = "The Drone Of Compassion (DOC) automatically heals those near it over time.",
                     ultimate_desc = "Call in a droppod full of high quality defensive gear.",
                     cooldown = 45,
                     charge = 5)

loba_list = list(name = "loba", alias = "translocating thief", 
                     season = 5, type = "support",
                     passive = "eye for quality", 
                     tactical = "burglar's best friend", 
                     ultimate = "black market boutique",
                 passive_desc = "Nearby epic and legendary loot can be seen through walls. The range is the same as Black Market Boutique.",
                 tactical_desc = "Teleport to hard-to-reach places or escape trouble quickly by throwing your jump drive bracelet.",
                 ultimate_desc = "Place a portable device that allows you to teleport nearby loot to your inventory. Each friendly or enemy Legend can take up to two items",
                 cooldown = 30,
                 charge = 2)

mirage_list = list(name = "mirage", alias = "holographic trickster", 
                     season = 0, type = "offensive",
                     passive = "now you see me...", 
                     tactical = "psyche out", 
                     ultimate = "life of the party",
                   passive_desc = "Automatically cloak when using Respawn Beacons and reviving teammates. Spawn a decoy and cloak when downed.",
                   tactical_desc = "Send out a holographic decoy to confuse the enemy. Press the utility action button to control the decoy.",
                   ultimate_desc = "Mirage deploys a team of controllable decoys to distract enemies.",
                   cooldown = 15,
                   charge = 1)

octane_list = list(name = "octane", alias = "high-speed daredevil", 
                     season = 1, type = "offensive",
                     passive = "swift mend", 
                     tactical = "stim", 
                     ultimate = "launch pad",
                   passive_desc = "Automatically restores health over time.",
                   tactical_desc = "Increase walk speed by 30% and sprint speed by 40% for 6 seconds. Costs Health to use. Reduction to slows while active.",
                   ultimate_desc = "Deploy a jump pad that catapults anyone through the air. Press the jump button to double jump.",
                   cooldown = 1,
                   charge = 1.5)

pathfinder_list = list(name = "pathfinder", alias = "forward scout", 
                     season = 0, type = "recon",
                     passive = "insider knowledge", 
                     tactical = "grappling hook", 
                     ultimate = "zipline gun",
                     passive_desc = "Scan a Survey Beacon to reduce the cooldown of Zipline Gun",
                     tactical_desc = "Grapple to get to out-of-reach places quickly.",
                     ultimate_desc = "Create a zipline for everyone to use.",
                     cooldown = 20,
                     charge = 2)

rampart_list = list(name = "rampart", alias = "base of fire", 
                     season = 6, type = "defensive",
                     passive = "modded loader", 
                     tactical = "amped cover", 
                     ultimate = "mobile minigun 'sheila'",
                    passive_desc = "Increased magazine/heat capacity and faster reloads/recharge when using LMGs and the Minigun.",
                    tactical_desc = "Build a crouch-cover wall, which deploys a full-cover amped wall that blocks incoming shots and amps outgoing shots. (Max: 5)",
                    ultimate_desc = "Wield a mobile minigun with a single high capacity magazine. Place it down for anyone to use as a stationary and reloadable turret (Max: 3)",
                    cooldown = 20,
                    charge = 2)

revenant_list = list(name = "revenant", alias = "synthetic nightmare", 
                     season = 4, type = "offensive",
                     passive = "stalker", 
                     tactical = "silence", 
                     ultimate = "death totem",
                     passive_desc = "You crouch walk faster and can climb walls higher.",
                     tactical_desc = "Throw a device that deals damage and disables enemy abilities for 15 seconds.",
                     ultimate_desc = "Drop a totem that protects users from death. Instead of getting killed or downed, you will return to the totem.",
                     cooldown = 25,
                     charge = 3)

seer_list = list(name = "seer", alias = "ambush artist", 
                     season = 10, type = "recon",
                     passive = "heart seeker", 
                     tactical = "focus of attention", 
                     ultimate = "exhibit",
                 passive_desc = "Hear and visualize the heartbeats of enemies within 75m when aiming down sights.",
                 tactical_desc = "Summon micro-drones to emit a delayed blast that goes through walls interrupting and revealing enemies.",
                 ultimate_desc = "Create a sphere of micro-drones that reveal the location of enemies moving quickly or firing their weapons within.",
                 cooldown = 30,
                 charge = 2)

valkyrie_list = list(name = "valkyrie", alias = "winged avenger", 
                     season = 9, type = "recon",
                     passive = "vtol jets", 
                     tactical = "missle swarm", 
                     ultimate = "skyward dive",
                     passive_desc = "Press the jump key while in the air to engage jetpack. You can switch between hold and toggle mode in the options menu.",
                     tactical_desc = "Fire a swarm of mini-rockets that damage and disorient the enemy.",
                     ultimate_desc = "Press once to prepare for launch. Teammates can interact with Valkyrie to join the launch. Press again to launch into the air and skydive.",
                     cooldown = 30,
                     charge = 3)

wattson_list = list(name = "wattson", alias = "static defender", 
                     season = 2, type = "defensive",
                     passive = "spark of genius", 
                     tactical = "perimeter security", 
                     ultimate = "interception pylon",
                    passive_desc = "Ultimate Accelerants fully charge Wattson's ultimate and she can carry more Ultimate Accelerants. Wattson slowly restores her shields over time.",
                    tactical_desc = "Create electrified fences by connecting nodes. Fences damage and slow enemies.",
                    ultimate_desc = "Place an electrified pylon that destroys incoming ordnance and repairs damaged shields. Standing near Pylons boosts Wattson's tactical recharge rate. (Max: 1)",
                    cooldown = 15,
                    charge = 3)

wraith_list = list(name = "wraith", alias = "interdimensional skirmisher", 
                     season = 0, type = "offensive",
                     passive = "voices from the void", 
                     tactical = "into the void", 
                     ultimate = "dimensional rift",
                   passive_desc = "A voice warns you when danger approaches. As far as you can tell, it's on your side.",
                   tactical_desc = "Reposition quickly through the safety of void space, avoiding all damage.",
                   ultimate_desc = "Link two locations with portals for 60 seconds, allowing anyone to use them.",
                   cooldown = 25,
                   charge = 3.5)
